name: Build and Release .NET Framework App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Install .NET Framework 4.8 Developer Pack
        run: choco install netfx-4.8-devpack -y

      - name: Restore NuGet packages
        run: nuget restore "Legilimens Starter.sln"

      - name: Build Solution
        run: msbuild "Legilimens Starter.sln" /p:Configuration=Release

      - name: Create Release Folder
        run: |
          mkdir release
          Copy-Item -Path "Legilimens Starter\bin\Release\*" -Destination "release" -Recurse

      - name: Zip Release
        run: Compress-Archive -Path release/* -DestinationPath Legilimens-Starter.zip

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: Legilimens-Starter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
