name: Build and Release .NET Framework App

on:
  push:
    tags:
      - 'v*'  # Triggers when a tag like "v1.0.0" is pushed
  workflow_dispatch:  # Allows manual runs

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Install .NET Framework 4.8 Developer Pack
        run: choco install netfx-4.8-devpack -y

      - name: Restore NuGet packages
        run: nuget restore "Legilimens Starter.sln"

      - name: Build Solution
        run: msbuild "Legilimens Starter.sln" /p:Configuration=Release

      - name: Create Release Folder
        run: |
          mkdir release
          Copy-Item -Path "Legilimens Starter\bin\Release\*" -Destination "release" -Recurse

      - name: Zip Release
        run: Compress-Archive -Path release/* -DestinationPath Legilimens-Starter.zip

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: Legilimens-Starter.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
